config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "explores#index"
  resources :explores
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
        can [:read, :create], Explore
        can :update, Explore, user_id: user.id
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/explore.rb
class Explore < ApplicationRecord
    belongs_to :user
    validates :title, presence: true
    has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :explores
  enum role: {normal: 0, admin: 1}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    rescue_from CanCan::AccessDenied do |exception|
        respond_to do |format| 
            format.html {
                # render file: "#{Rails.root}/public/401", altert: exception.message
                redirect_to root_path, alert: exception.message
            }
        end
    end
end

app/controllers/explores_controller.rb
class ExploresController < ApplicationController
  before_action :set_explore, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  # GET /explores or /explores.json
  def index
    @explores = Explore.all
  end

  # GET /explores/1 or /explores/1.json
  def show
  end

  # GET /explores/new
  def new
    @explore = Explore.new
  end

  # GET /explores/1/edit
  def edit
  end

  # POST /explores or /explores.json
  def create
    @explore = Explore.new(explore_params)
    @explore.user_id = current_user.id
    @explore.photo.attach(params[:explore][:photo])

    respond_to do |format|
      if @explore.save
        format.html { redirect_to @explore, notice: "Explore was successfully created." }
        format.json { render :show, status: :created, location: @explore }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @explore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /explores/1 or /explores/1.json
  def update
    respond_to do |format|
      if @explore.update(explore_params)
        format.html { redirect_to @explore, notice: "Explore was successfully updated." }
        format.json { render :show, status: :ok, location: @explore }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @explore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /explores/1 or /explores/1.json
  def destroy
    @explore.destroy
    respond_to do |format|
      format.html { redirect_to explores_url, notice: "Explore was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_explore
      @explore = Explore.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def explore_params
      params.require(:explore).permit(:title, :description, :price, :user_id, :email, :user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/explores_helper.rb
module ExploresHelper
end

app/views/explores/_form.html.erb
<%= form_with(model: explore, local: true) do |form| %>
  <% if explore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(explore.errors.count, "error") %> prohibited this explore from being saved:</h2>

      <ul>
        <% explore.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>
  
  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/explores/edit.html.erb
<h1>Editing Explore</h1>

<%= render 'form', explore: @explore %>

<%= link_to 'Show', @explore %> |
<%= link_to 'Back', explores_path %>

app/views/explores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Explores</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @explores.each do |explore| %>
      <tr>
        <td><%= explore.title %></td>
        <td><%= explore.description %></td>
        <td><%= explore.price %></td>
        <td><%= link_to 'Show', explore %></td>
      <% if explore.user_id == current_user %>
          <td><%= link_to 'Edit', edit_explore_path(explore) %></td>
          <td><%= link_to 'Destroy', explore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
       
  
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/explores/new.html.erb
<h1>New Explore</h1>

<%if user_signed_in?%>
    <%= render 'form', explore: @explore %>

    <%= link_to 'Back', explores_path %>
<%else%>
    <h3>Please sign in to create a explore</h3>
<%end%>

app/views/explores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @explore.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @explore.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @explore.price %>
</p>

<%if @explore.photo.attached?%>
  <p>
    <strong>Photo:</strong>
    <%= image_tag @explore.photo %>
  </p>

<%else%>
<%end%>

<%= link_to 'Edit', edit_explore_path(@explore) %> |
<%= link_to 'Back', explores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WearMarketplaceApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render"shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<header>
<nav class="navbar navbar-expand-sm navbar-dark bg-dark" aria-label="Third navbar example">
    <div class="container-fluid">
         <%= link_to "Wear", explores_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample03">
        <ul class="navbar-nav me-auto mb-2 mb-sm-0">
          <li class="nav-item">
            <%# <a class="nav-link active" aria-current="page" href="#">Listing</a> %>
            <%= link_to "Listing", explores_path, class: "nav-link active" %>
          </li>

          <li class="nav-item">
            <%# <a class="nav-link active" aria-current="page" href="#">Add New Listing</a> %>
            <%= link_to "Add New Listing", new_explore_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
          <% if user_signed_in? %>
            <%# logout button (only show this when logged in) %>    
            <%= link_to "Log Out", destroy_user_session_path, method:"delete", class: "nav-link active" %>
          <% else %>
            <%# login button (only show this when logged out) %> 
            <%= link_to "Log In", new_user_session_path, class: "nav-link active" %>
          <% end %>         
          </li>
        </ul>
        <%# Add this back when search implemented %>
        <%# <form>
          <input class="form-control" type="text" placeholder="Search" aria-label="Search">
        </form> %>
      </div>
    </div>
  </nav>
</header>